// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEiYlWkzdl0ItToPH3kVXt82d7SN822l0',
    appId: '1:442972139102:web:6a4bb6290424fec9bc4ecf',
    messagingSenderId: '442972139102',
    projectId: 'presence-ecole',
    authDomain: 'presence-ecole.firebaseapp.com',
    storageBucket: 'presence-ecole.firebasestorage.app',
    measurementId: 'G-J41WNLXN07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRpd0VIMYDzoOUKy6leqvp51e7rF0qrcM',
    appId: '1:442972139102:android:c80b61e1ddcdc828bc4ecf',
    messagingSenderId: '442972139102',
    projectId: 'presence-ecole',
    storageBucket: 'presence-ecole.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCQ-DVBapqyeyAkFhiFei8mc0VOtg079Q',
    appId: '1:442972139102:ios:1b68c5498789a99dbc4ecf',
    messagingSenderId: '442972139102',
    projectId: 'presence-ecole',
    storageBucket: 'presence-ecole.firebasestorage.app',
    iosBundleId: 'com.example.detectionFasciale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCQ-DVBapqyeyAkFhiFei8mc0VOtg079Q',
    appId: '1:442972139102:ios:1b68c5498789a99dbc4ecf',
    messagingSenderId: '442972139102',
    projectId: 'presence-ecole',
    storageBucket: 'presence-ecole.firebasestorage.app',
    iosBundleId: 'com.example.detectionFasciale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEiYlWkzdl0ItToPH3kVXt82d7SN822l0',
    appId: '1:442972139102:web:e7873a2d8461376abc4ecf',
    messagingSenderId: '442972139102',
    projectId: 'presence-ecole',
    authDomain: 'presence-ecole.firebaseapp.com',
    storageBucket: 'presence-ecole.firebasestorage.app',
    measurementId: 'G-9RY8Y9TY5C',
  );
}
